senta

diff --git a/GoogleAuthDemo/docker-compose.yml b/GoogleAuthDemo/docker-compose.yml
--- a/GoogleAuthDemo/docker-compose.yml
+++ b/GoogleAuthDemo/docker-compose.yml
@@ -20,256 +20,197 @@ services:
     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
 
-  sql_server_container:
-    image: mcr.microsoft.com/mssql/server:latest
-    environment:
-      - ACCEPT_EULA=Y
-      - SA_PASSWORD=Yaquim123*
-    ports:
-      - "1433:1433"
-    networks:
-      - backend
-
   grafana:
     image: grafana/grafana
     ports:
       - "3001:3000"
     depends_on:
       - prometheus
+
+      
   elasticsearch:
-    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
-    ports:
-      - "9200:9200"
-    environment:
-      - node.name=es01
-      - cluster.name=docker-cluster
-      - discovery.type=single-node
-      - bootstrap.memory_lock=true
-      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
-    ulimits:
-      memlock:
-        soft: -1
-        hard: -1
+   container_name: elasticsearch
+   image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
+   ports:
+    - 9200:9200
+   volumes:
+    - elasticsearch-data:/usr/share/elasticsearch/data
+   environment:
+    - xpack.monitoring.enabled=true
+    - xpack.watcher.enabled=false
+    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
+    - discovery.type=single-node
+    - ELASTICSEARCH_USERNAME=elastic
+    - ELASTICSEARCH_PASSWORD=Yaquim123*
+   networks:
+    - elastic
 
   kibana:
-    image: docker.elastic.co/kibana/kibana:8.13.2
-    ports:
-      - "5601:5601"
-    environment:
-      - ELASTICSEARCH_HOSTS=http://localhost:9200
-      - ELASTICSEARCH_USERNAME=kibana_system
-      - ELASTICSEARCH_PASSWORD=changeme
-    depends_on:
-      - elasticsearch
-
+   container_name: kibana
+   image: docker.elastic.co/kibana/kibana:8.10.2
+   ports:
+    - 5601:5601
+   depends_on:
+    - elasticsearch
+   environment:
+    - ELASTICSEARCH_URL=http://localhost:9200
+    - ELASTICSEARCH_USERNAME=elastic
+    - ELASTICSEARCH_PASSWORD=Yaquim123*
+   networks:
+    - elastic
+  
 networks:
-  backend:
+  elastic:
     driver: bridge
 
+volumes:
+  elasticsearch-data:
+
+#   grafana:
+#     image: grafana/grafana
+#     ports:
+#       - "3001:3000"
+#     depends_on:
+#       - prometheus
+#     networks:
+#       - backend
 
 #   setup:
 #     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
-#     volumes:
-#       - certs:/usr/share/elasticsearch/config/certs
+#     container_name: setup
 #     user: "0"
 #     command: >
 #       bash -c '
+#         echo "Setup...";
 #         if [ x${ELASTIC_PASSWORD} == x ]; then
 #           echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
 #           exit 1;
-#         elif [ x${KIBANA_PASSWORD} == x ]; then
+#         fi;
+#         if [ x${KIBANA_PASSWORD} == x ]; then
 #           echo "Set the KIBANA_PASSWORD environment variable in the .env file";
 #           exit 1;
 #         fi;
-#         if [ ! -f config/certs/ca.zip ]; then
-#           echo "Creating CA";
-#           bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
-#           unzip config/certs/ca.zip -d config/certs;
+#         if [ x${SERVICEUSER_PASSWORD} == x ]; then
+#           echo "Set the SERVICEUSER_PASSWORD environment variable in the .env file";
+#           exit 1;
 #         fi;
-#         if [ ! -f config/certs/certs.zip ]; then
-#           echo "Creating certs";
-#           echo -ne \
-#           "instances:\n"\
-#           "  - name: es01\n"\
-#           "    dns:\n"\
-#           "      - es01\n"\
-#           "      - localhost\n"\
-#           "    ip:\n"\
-#           "      - 127.0.0.1\n"\
-#           "  - name: es02\n"\
-#           "    dns:\n"\
-#           "      - es02\n"\
-#           "      - localhost\n"\
-#           "    ip:\n"\
-#           "      - 127.0.0.1\n"\
-#           "  - name: es03\n"\
-#           "    dns:\n"\
-#           "      - es03\n"\
-#           "      - localhost\n"\
-#           "    ip:\n"\
-#           "      - 127.0.0.1\n"\
-#           > config/certs/instances.yml;
-#           bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
-#           unzip config/certs/certs.zip -d config/certs;
+#         if [ ${SERVICEUSER_USERNAME} == elastic ]; then
+#           echo "SERVICEUSER_USERNAME environment variable can not be elastic. Change it in the .env file";
+#           exit 1;
 #         fi;
-#         echo "Setting file permissions"
-#         chown -R root:root config/certs;
-#         find . -type d -exec chmod 750 \{\} \;;
-#         find . -type f -exec chmod 640 \{\} \;;
-#         echo "Waiting for Elasticsearch availability";
-#         until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
-#         echo "Setting kibana_system password";
-#         until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
-#         echo "All done!";
+#         if [ "x${APP_LOGS_INDEX}" == "x" ]; then
+#           echo "Set APP_LOGS_INDEX environment variable in the .env file";
+#           exit 1;
+#         fi;
+#         touch config/done;
+#         echo "Waiting for Elasticsearch availability...";
+#         until curl -s http://elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
+#         echo "Setting kibana_system password...";
+#         until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
+#         echo "Setting service user role...";
+#         until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch:9200/_security/role/service_user_role?pretty -d "{\"indices\": [{\"names\": [ \"${APP_LOGS_INDEX}\" ],\"privileges\": [\"all\"]}]}" | grep -q "created"; do sleep 10; done;
+#         echo "Setting service user...";
+#         until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/${SERVICEUSER_USERNAME} -d "{\"password\":\"${SERVICEUSER_PASSWORD}\",\"full_name\":\"${SERVICEUSER_FULLNAME}\",\"email\":\"${SERVICEUSER_EMAIL}\",\"roles\":[\"reporting_user\",\"kibana_admin\",\"service_user_role\"]}" | grep -q "created"; do sleep 10; done;
+#         echo "All done!"
 #       '
 #     healthcheck:
-#       test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
+#       test: ["CMD-SHELL", "[ -f config/done ]"]
 #       interval: 1s
 #       timeout: 5s
-#       retries: 120
+#       retries: 300
+#     networks:
+#       - elastic
 
-#   es01:
+#   app:
+#     build:
+#       context: ./WebLibraryApp
+#       dockerfile: Dockerfile
+#     container_name: app
+#     environment:
+#       - USE_DEVELOPMENT_SEED=TRUE
+#       - USE_SERILOG_DEBUGGING=TRUE
+#       - ElasticsearchOptions:ConnectionUsername=${SERVICEUSER_USERNAME}
+#       - ElasticsearchOptions:ConnectionPassword=${SERVICEUSER_PASSWORD}
+#     ports:
+#       - "8040:80"
+#       - "44340:443"
+#     depends_on:
+#       sqlServer:
+#         condition: service_healthy
+#       kibana:
+#         condition: service_healthy
+#     networks:
+#       - elastic
+        
+#   sqlServer:
+#     image: "mcr.microsoft.com/mssql/server:2019-latest"
 #     depends_on:
 #       setup:
 #         condition: service_healthy
-#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
+#     container_name: sqlServer
 #     volumes:
-#       - certs:/usr/share/elasticsearch/config/certs
-#       - esdata01:/usr/share/elasticsearch/data
+#       - sqlserverdata:/data
+#     environment:
+#       - ACCEPT_EULA=Y
+#       - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
+#     ports:
+#       - "1433:1433"
+#     healthcheck:
+#       test: [
+#         "CMD", "/opt/mssql-tools/bin/sqlcmd", 
+#         "-U", "sa", 
+#         "-P", "${MSSQL_PASSWORD}", 
+#         "-Q", "SELECT \"READY\""]
+#       interval: 15s
+#       timeout: 5s
+#       retries: 300
+#     networks:
+#       - elastic
+
+#   elasticsearch:
+#     depends_on:
+#       setup:
+#         condition: service_healthy
+#     container_name: elasticsearch
+#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
 #     ports:
 #       - ${ES_PORT}:9200
+#     volumes:
+#       - elasticsearch-data:/usr/share/elasticsearch/data
 #     environment:
-#       - node.name=es01
 #       - cluster.name=${CLUSTER_NAME}
-#       - cluster.initial_master_nodes=es01,es02,es03
-#       - discovery.seed_hosts=es02,es03
+#       - discovery.type=single-node
+#       - xpack.watcher.enabled=false
+#       - xpack.security.enabled=true
 #       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
-#       - bootstrap.memory_lock=true
-#       - xpack.security.enabled=true
-#       - xpack.security.http.ssl.enabled=true
-#       - xpack.security.http.ssl.key=certs/es01/es01.key
-#       - xpack.security.http.ssl.certificate=certs/es01/es01.crt
-#       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.enabled=true
-#       - xpack.security.transport.ssl.key=certs/es01/es01.key
-#       - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
-#       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.verification_mode=certificate
-#       - xpack.license.self_generated.type=${LICENSE}
-#     mem_limit: ${MEM_LIMIT}
-#     ulimits:
-#       memlock:
-#         soft: -1
-#         hard: -1
+#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
 #     healthcheck:
 #       test:
 #         [
 #           "CMD-SHELL",
-#           "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
+#           "curl -s -I -u elastic:${ELASTIC_PASSWORD} http://localhost:9200 | grep -q 'HTTP/1.1 200 OK'",
 #         ]
 #       interval: 10s
 #       timeout: 10s
-#       retries: 120
-
-#   es02:
-#     depends_on:
-#       - es01
-#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
-#     volumes:
-#       - certs:/usr/share/elasticsearch/config/certs
-#       - esdata02:/usr/share/elasticsearch/data
-#     environment:
-#       - node.name=es02
-#       - cluster.name=${CLUSTER_NAME}
-#       - cluster.initial_master_nodes=es01,es02,es03
-#       - discovery.seed_hosts=es01,es03
-#       - bootstrap.memory_lock=true
-#       - xpack.security.enabled=true
-#       - xpack.security.http.ssl.enabled=true
-#       - xpack.security.http.ssl.key=certs/es02/es02.key
-#       - xpack.security.http.ssl.certificate=certs/es02/es02.crt
-#       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.enabled=true
-#       - xpack.security.transport.ssl.key=certs/es02/es02.key
-#       - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
-#       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.verification_mode=certificate
-#       - xpack.license.self_generated.type=${LICENSE}
-#     mem_limit: ${MEM_LIMIT}
-#     ulimits:
-#       memlock:
-#         soft: -1
-#         hard: -1
-#     healthcheck:
-#       test:
-#         [
-#           "CMD-SHELL",
-#           "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
-#         ]
-#       interval: 10s
-#       timeout: 10s
-#       retries: 120
-
-#   es03:
-#     depends_on:
-#       - es02
-#     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
-#     volumes:
-#       - certs:/usr/share/elasticsearch/config/certs
-#       - esdata03:/usr/share/elasticsearch/data
-#     environment:
-#       - node.name=es03
-#       - cluster.name=${CLUSTER_NAME}
-#       - cluster.initial_master_nodes=es01,es02,es03
-#       - discovery.seed_hosts=es01,es02
-#       - bootstrap.memory_lock=true
-#       - xpack.security.enabled=true
-#       - xpack.security.http.ssl.enabled=true
-#       - xpack.security.http.ssl.key=certs/es03/es03.key
-#       - xpack.security.http.ssl.certificate=certs/es03/es03.crt
-#       - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.enabled=true
-#       - xpack.security.transport.ssl.key=certs/es03/es03.key
-#       - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
-#       - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
-#       - xpack.security.transport.ssl.verification_mode=certificate
-#       - xpack.license.self_generated.type=${LICENSE}
-#     mem_limit: ${MEM_LIMIT}
-#     ulimits:
-#       memlock:
-#         soft: -1
-#         hard: -1
-#     healthcheck:
-#       test:
-#         [
-#           "CMD-SHELL",
-#           "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
-#         ]
-#       interval: 10s
-#       timeout: 10s
-#       retries: 120
+#       retries: 300
+#     networks:
+#       - elastic
 
 #   kibana:
 #     depends_on:
-#       es01:
+#       elasticsearch:
 #         condition: service_healthy
-#       es02:
-#         condition: service_healthy
-#       es03:
-#         condition: service_healthy
+#     container_name: kibana
 #     image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
 #     volumes:
-#       - certs:/usr/share/kibana/config/certs
 #       - kibanadata:/usr/share/kibana/data
 #     ports:
 #       - ${KIBANA_PORT}:5601
 #     environment:
 #       - SERVERNAME=kibana
-#       - ELASTICSEARCH_HOSTS=https://es01:9200
 #       - ELASTICSEARCH_USERNAME=kibana_system
 #       - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
-#       - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
-#     mem_limit: ${MEM_LIMIT}
+#       - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
 #     healthcheck:
 #       test:
 #         [
@@ -278,16 +219,18 @@ networks:
 #         ]
 #       interval: 10s
 #       timeout: 10s
-#       retries: 120
+#       retries: 300
+#     networks:
+#       - elastic
+  
+# networks:
+#   elastic:
+#     driver: bridge
 
 # volumes:
-#   certs:
+#   elasticsearch-data:
 #     driver: local
-#   esdata01:
-#     driver: local
-#   esdata02:
-#     driver: local
-#   esdata03:
+#   sqlserverdata:
 #     driver: local
 #   kibanadata:
 #     driver: local
